version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginxcontainer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build/web:/usr/share/nginx/html
